### ISSUE TITLE
Migrate Firebase

### ISSUE THREAD

**Issue by sidhshar** [S3Infosoft/s3-loyalty-mobile#10]
Migrate Firebase to S3 domain

**Comment by dev-sourabh** [comment]
please give permission of firebase on sharmasourabh121.ss@gmail.com

**Comment by sidhshar** [comment]
Granted to you and Arushi. Can you check now?

**Comment by dev-sourabh** [comment]
> Granted to you and Arushi. Can you check now?

Yes Sir

**Comment by dev-sourabh** [comment]
master branch google-services.json updated to new firebase
